/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    organizations: Organization;
    agencies: Agency;
    proposals: Proposal;
    rfps: Rfp;
    requirements: Requirement;
    documents: Document;
    staff: Staff;
    projects: Project;
    rates: Rate;
    subconsultants: Subconsultant;
    certifications: Certification;
    'content-blocks': ContentBlock;
    templates: Template;
    'audit-events': AuditEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    agencies: AgenciesSelect<false> | AgenciesSelect<true>;
    proposals: ProposalsSelect<false> | ProposalsSelect<true>;
    rfps: RfpsSelect<false> | RfpsSelect<true>;
    requirements: RequirementsSelect<false> | RequirementsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    rates: RatesSelect<false> | RatesSelect<true>;
    subconsultants: SubconsultantsSelect<false> | SubconsultantsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    'content-blocks': ContentBlocksSelect<false> | ContentBlocksSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'admin' | 'proposal-manager' | 'contributor' | 'viewer';
  /**
   * Allows viewing finance-sensitive rate fields and financial documents.
   */
  financeAccess?: boolean | null;
  organization?: (string | null) | Organization;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: string;
  name: string;
  tenantKey: string;
  status: 'active' | 'implementation' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agencies".
 */
export interface Agency {
  id: string;
  name: string;
  agencyCode: string;
  organization: string | Organization;
  recurringRequirements?:
    | {
        requirement: string;
        id?: string | null;
      }[]
    | null;
  strategyNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposals".
 */
export interface Proposal {
  id: string;
  title: string;
  organization: string | Organization;
  agency?: (string | null) | Agency;
  pursuitStatus: 'planning' | 'rfp-intake' | 'drafting' | 'internal-review' | 'submitted' | 'awarded' | 'not-selected';
  riskLevel: 'low' | 'medium' | 'high';
  dueDate?: string | null;
  estimatedValue?: number | null;
  lead?: (string | null) | User;
  summary?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rfps".
 */
export interface Rfp {
  id: string;
  title: string;
  organization: string | Organization;
  proposal?: (string | null) | Proposal;
  sourceDocument?: (string | null) | Document;
  dueDate?: string | null;
  questionDeadline?: string | null;
  reviewStatus: 'uploaded' | 'extracting' | 'needs-human-review' | 'confirmed';
  extractedSummary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  title: string;
  organization: string | Organization;
  proposal?: (string | null) | Proposal;
  documentType:
    | 'rfp'
    | 'addendum'
    | 'proposal-draft'
    | 'rate-sheet'
    | 'subconsultant-contract'
    | 'certification'
    | 'project-sheet'
    | 'other';
  sensitivity: 'general' | 'internal' | 'finance-restricted' | 'contract-restricted';
  restrictedNotes?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requirements".
 */
export interface Requirement {
  id: string;
  title: string;
  organization: string | Organization;
  rfp: string | Rfp;
  category: 'scope' | 'submission' | 'evaluation' | 'form' | 'timeline' | 'compliance';
  evidenceState: 'strong' | 'partial' | 'none';
  reviewStatus: 'needs-review' | 'confirmed' | 'rejected';
  sourceCitation?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: string;
  name: string;
  organization: string | Organization;
  role: string;
  yearsExperience?: number | null;
  availability?: ('available' | 'limited' | 'needs-confirmation') | null;
  certifications?: (string | Certification)[] | null;
  projectHistory?: (string | Project)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: string;
  name: string;
  organization: string | Organization;
  certificationType: 'mbe' | 'wbe' | 'sdvob' | 'other';
  issuer?: string | null;
  expirationDate?: string | null;
  status?: ('current' | 'expiring-soon' | 'expired' | 'needs-verification') | null;
  document?: (string | null) | Document;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  name: string;
  organization: string | Organization;
  agency?: (string | null) | Agency;
  client?: string | null;
  projectType?: string | null;
  budget?: number | null;
  disciplines?:
    | {
        discipline: string;
        id?: string | null;
      }[]
    | null;
  websiteStatus?: ('not-reviewed' | 'ready' | 'on-website' | 'needs-update') | null;
  summary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rates".
 */
export interface Rate {
  id: string;
  title: string;
  organization: string | Organization;
  firm: string;
  agency?: (string | null) | Agency;
  bareRate: number;
  multiplier?: number | null;
  loadedRate: number;
  effectiveDate?: string | null;
  expirationDate?: string | null;
  contractReference?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subconsultants".
 */
export interface Subconsultant {
  id: string;
  name: string;
  organization: string | Organization;
  status?: ('active' | 'needs-review' | 'inactive') | null;
  capabilities?:
    | {
        capability: string;
        id?: string | null;
      }[]
    | null;
  disciplines?:
    | {
        discipline: string;
        id?: string | null;
      }[]
    | null;
  certifications?: (string | Certification)[] | null;
  contractDocuments?: (string | Document)[] | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-blocks".
 */
export interface ContentBlock {
  id: string;
  title: string;
  organization: string | Organization;
  category: 'company-boilerplate' | 'technical-approach' | 'discipline-section' | 'cover-letter' | 'other';
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status?: ('draft' | 'approved' | 'retired') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: string;
  title: string;
  organization: string | Organization;
  templateType: 'proposal' | 'resume' | 'project-sheet';
  agency?: (string | null) | Agency;
  status?: ('draft' | 'approved' | 'retired') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: string;
  eventType: string;
  organization?: (string | null) | Organization;
  actor?: (string | null) | User;
  targetCollection?: string | null;
  targetId?: string | null;
  summary: string;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'organizations';
        value: string | Organization;
      } | null)
    | ({
        relationTo: 'agencies';
        value: string | Agency;
      } | null)
    | ({
        relationTo: 'proposals';
        value: string | Proposal;
      } | null)
    | ({
        relationTo: 'rfps';
        value: string | Rfp;
      } | null)
    | ({
        relationTo: 'requirements';
        value: string | Requirement;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'staff';
        value: string | Staff;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'rates';
        value: string | Rate;
      } | null)
    | ({
        relationTo: 'subconsultants';
        value: string | Subconsultant;
      } | null)
    | ({
        relationTo: 'certifications';
        value: string | Certification;
      } | null)
    | ({
        relationTo: 'content-blocks';
        value: string | ContentBlock;
      } | null)
    | ({
        relationTo: 'templates';
        value: string | Template;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: string | AuditEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  financeAccess?: T;
  organization?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  tenantKey?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agencies_select".
 */
export interface AgenciesSelect<T extends boolean = true> {
  name?: T;
  agencyCode?: T;
  organization?: T;
  recurringRequirements?:
    | T
    | {
        requirement?: T;
        id?: T;
      };
  strategyNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposals_select".
 */
export interface ProposalsSelect<T extends boolean = true> {
  title?: T;
  organization?: T;
  agency?: T;
  pursuitStatus?: T;
  riskLevel?: T;
  dueDate?: T;
  estimatedValue?: T;
  lead?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rfps_select".
 */
export interface RfpsSelect<T extends boolean = true> {
  title?: T;
  organization?: T;
  proposal?: T;
  sourceDocument?: T;
  dueDate?: T;
  questionDeadline?: T;
  reviewStatus?: T;
  extractedSummary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requirements_select".
 */
export interface RequirementsSelect<T extends boolean = true> {
  title?: T;
  organization?: T;
  rfp?: T;
  category?: T;
  evidenceState?: T;
  reviewStatus?: T;
  sourceCitation?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  organization?: T;
  proposal?: T;
  documentType?: T;
  sensitivity?: T;
  restrictedNotes?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  name?: T;
  organization?: T;
  role?: T;
  yearsExperience?: T;
  availability?: T;
  certifications?: T;
  projectHistory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  organization?: T;
  agency?: T;
  client?: T;
  projectType?: T;
  budget?: T;
  disciplines?:
    | T
    | {
        discipline?: T;
        id?: T;
      };
  websiteStatus?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rates_select".
 */
export interface RatesSelect<T extends boolean = true> {
  title?: T;
  organization?: T;
  firm?: T;
  agency?: T;
  bareRate?: T;
  multiplier?: T;
  loadedRate?: T;
  effectiveDate?: T;
  expirationDate?: T;
  contractReference?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subconsultants_select".
 */
export interface SubconsultantsSelect<T extends boolean = true> {
  name?: T;
  organization?: T;
  status?: T;
  capabilities?:
    | T
    | {
        capability?: T;
        id?: T;
      };
  disciplines?:
    | T
    | {
        discipline?: T;
        id?: T;
      };
  certifications?: T;
  contractDocuments?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  name?: T;
  organization?: T;
  certificationType?: T;
  issuer?: T;
  expirationDate?: T;
  status?: T;
  document?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-blocks_select".
 */
export interface ContentBlocksSelect<T extends boolean = true> {
  title?: T;
  organization?: T;
  category?: T;
  body?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  title?: T;
  organization?: T;
  templateType?: T;
  agency?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  eventType?: T;
  organization?: T;
  actor?: T;
  targetCollection?: T;
  targetId?: T;
  summary?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}